export default {
  title: {
    text: 'Gantt Chart View',
  },
  series: [
    {
      name: 'Project 1',

      data: [
        {
          name: 'Start prototype',
          id: 'a',
          completed: 1,
          start: Date.UTC(2014, 10, 18),
          end: Date.UTC(2014, 10, 20),
          developer: 'John Doe',
          dependencies: [],
          y: 0,
        },
        {
          name: 'Product Launch',
          id: 0,
          completed: 1,
          start: Date.UTC(2014, 10, 18),
          end: Date.UTC(2014, 10, 20),
          developer: 'Qwerty',
          dependencies: ['a'],
          y: 1,
        },
        {
          id: 'c',
          name: 'Develop',
          start: Date.UTC(2014, 10, 20),
          end: Date.UTC(2014, 10, 25),
          dependency: 'prototype',
          developer: 'John Doe',
          dependencies: [0],
          y: 2,
        },
        {
          id: 'd',
          name: 'Run acceptance tests',
          start: Date.UTC(2014, 10, 23),
          end: Date.UTC(2014, 10, 26),
          developer: 'John Doe',
          dependencies: [0, 'c'],
          y: 3,
        },
        {
          name: 'Test prototype',
          id: 'e',
          start: Date.UTC(2014, 10, 27),
          end: Date.UTC(2014, 10, 29),
          dependency: ['a', 0],
          developer: 'John Doe',
          y: 4,
        },
        {
          name: 'Test prototype',
          id: 'x',
          start: Date.UTC(2014, 10, 27),
          end: Date.UTC(2014, 10, 29),
          dependency: ['a', 0, 'c', 'd'],
          developer: 'aa',
          y: 5,
        },
        {
          name: 'Random shit',
          id: 'x',
          start: Date.UTC(2014, 11, 27),
          end: Date.UTC(2014, 10, 29),
          dependency: [0],
          developer: 'xx',
          y: 3,
        },
      ],
    },
  ],
};
